# Generated by Django 3.1.1 on 2021-05-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_registration',
            new_name='User',
        ),
    ]
